// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfdpjdoeoknoogicibtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZHBqZG9lb2tub29naWNpYnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjY2MzMsImV4cCI6MjA3Mzg0MjYzM30.Mca8duxdRIWMS2MLsFBWEP4OO6bwLwDkcdZUCdHpccg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});